### ISSUE TITLE
GraalVM Native Image fails

### ISSUE THREAD

**Issue by sdelamo** [micronaut-guides/micronaut-oauth2-okta#6]
# Steps to reproduce

- Clone `graalmv` branch
- Generate Guide with `clean pG`
- Generate native image and run.

```
 % ./micronautguide -Xmx68m
10:55:41.532 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to retrieve OpenID configuration for okta
io.micronaut.context.exceptions.BeanInstantiationException: Failed to retrieve OpenID configuration for okta
	at io.micronaut.security.oauth2.client.OpenIdClientFactory.lambda$openIdConfiguration$0(OpenIdClientFactory.java:93)
	at java.util.Optional.map(Optional.java:215)
	at io.micronaut.security.oauth2.client.OpenIdClientFactory.openIdConfiguration(OpenIdClientFactory.java:83)
	at io.micronaut.security.oauth2.client.$OpenIdClientFactory$OpenIdConfiguration0Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1585)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:774)
	at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:706)
	at io.micronaut.context.BeanContext.createBean(BeanContext.java:127)
	at io.micronaut.security.oauth2.client.OpenIdClientFactory.openIdClient(OpenIdClientFactory.java:129)
	at io.micronaut.security.oauth2.client.$OpenIdClientFactory$OpenIdClient1Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:109)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1598)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1989)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1963)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1102)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:615)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:103)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1598)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2630)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2552)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:911)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1114)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1752)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1109)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:984)
	at io.micronaut.security.oauth2.routes.$OauthRouteBuilderDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1598)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2630)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2552)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:911)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1114)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1752)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1109)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:984)
	at io.micronaut.web.router.$DefaultRouterDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1598)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1989)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1963)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1082)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1598)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2307)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1989)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1963)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1102)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:615)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:135)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:307)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:293)
	at example.micronaut.Application.main(Application.java:8)
Caused by: io.micronaut.http.client.exceptions.HttpClientResponseException: Error decoding HTTP response body: Error decoding JSON stream for type [class io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata]: Class com.fasterxml.jackson.databind.PropertyNamingStrategy$SnakeCaseStrategy has no default (no arg) constructor
 at [Source: (byte[])"{"issuer":"https://dev-265911.oktapreview.com/oauth2/default","authorization_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/authorize","token_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/token","userinfo_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/userinfo","registration_endpoint":"https://dev-265911.oktapreview.com/oauth2/v1/clients","jwks_uri":"https://dev-265911.oktapreview.com/oauth2/default/v1/keys","response_types_supported":["code",""[truncated 1604 bytes]; line: 1, column: 1]
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1910)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1787)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:185)
	at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:180)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [class io.micronaut.security.oauth2.client.DefaultOpenIdProviderMetadata]: Class com.fasterxml.jackson.databind.PropertyNamingStrategy$SnakeCaseStrategy has no default (no arg) constructor
 at [Source: (byte[])"{"issuer":"https://dev-265911.oktapreview.com/oauth2/default","authorization_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/authorize","token_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/token","userinfo_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/userinfo","registration_endpoint":"https://dev-265911.oktapreview.com/oauth2/v1/clients","jwks_uri":"https://dev-265911.oktapreview.com/oauth2/default/v1/keys","response_types_supported":["code",""[truncated 1604 bytes]; line: 1, column: 1]
	at io.micronaut.jackson.codec.JsonMediaTypeCodec.decode(JsonMediaTypeCodec.java:139)
	at io.micronaut.http.client.FullNettyClientHttpResponse.convertByteBuf(FullNettyClientHttpResponse.java:250)
	at io.micronaut.http.client.FullNettyClientHttpResponse.lambda$getBody$1(FullNettyClientHttpResponse.java:191)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at io.micronaut.http.client.FullNettyClientHttpResponse.getBody(FullNettyClientHttpResponse.java:168)
	at io.micronaut.http.client.FullNettyClientHttpResponse.<init>(FullNettyClientHttpResponse.java:101)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1840)
	... 53 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Class com.fasterxml.jackson.databind.PropertyNamingStrategy$SnakeCaseStrategy has no default (no arg) constructor
 at [Source: (byte[])"{"issuer":"https://dev-265911.oktapreview.com/oauth2/default","authorization_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/authorize","token_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/token","userinfo_endpoint":"https://dev-265911.oktapreview.com/oauth2/default/v1/userinfo","registration_endpoint":"https://dev-265911.oktapreview.com/oauth2/v1/clients","jwks_uri":"https://dev-265911.oktapreview.com/oauth2/default/v1/keys","response_types_supported":["code",""[truncated 1604 bytes]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:221)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4191)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4010)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3092)
	at io.micronaut.jackson.codec.JsonMediaTypeCodec.decode(JsonMediaTypeCodec.java:136)
	... 59 common frames omitted
```

**Comment by morki** [comment]
The same for me, no errors during build, just failing on runtime

**Comment by morki** [comment]
@sdelame it was fixed here https://github.com/micronaut-projects/micronaut-security/issues/176

Can you try with 1.3.2 BUILD SNAPSHOT and close if it works for you? For me, it is working now.
